# Generated by Django 3.1 on 2023-05-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230507_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=200, upload_to='photos/products'),
        ),
    ]
