# Generated by Django 3.1 on 2023-05-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20230413_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_img',
        ),
    ]
